create table DiningHall (
	diningHall VARCHAR(50),
	address VARCHAR(50)
);
insert into DiningHall (diningHall, address) values ('Snaptags', '7327 Anthes Avenue');
insert into DiningHall (diningHall, address) values ('Zooxo', '1 Elka Point');
insert into DiningHall (diningHall, address) values ('Realbridge', '7 Namekagon Trail');
insert into DiningHall (diningHall, address) values ('Skaboo', '72133 Hallows Circle');
insert into DiningHall (diningHall, address) values ('Demizz', '351 Blaine Alley');
insert into DiningHall (diningHall, address) values ('Yodo', '66373 Anzinger Circle');
insert into DiningHall (diningHall, address) values ('Realmix', '36577 Grim Street');
insert into DiningHall (diningHall, address) values ('Edgeify', '52822 Ohio Street');
insert into DiningHall (diningHall, address) values ('Oyoloo', '64304 Scoville Court');
insert into DiningHall (diningHall, address) values ('Yotz', '8696 Northfield Circle');
insert into DiningHall (diningHall, address) values ('Dazzlesphere', '685 Oak Valley Road');
insert into DiningHall (diningHall, address) values ('Avamm', '53872 Oriole Pass');
insert into DiningHall (diningHall, address) values ('Omba', '051 Cottonwood Place');
insert into DiningHall (diningHall, address) values ('Kwilith', '489 Sachtjen Street');
insert into DiningHall (diningHall, address) values ('Lazzy', '3898 Emmet Point');
insert into DiningHall (diningHall, address) values ('Babbleopia', '1378 Talmadge Court');
insert into DiningHall (diningHall, address) values ('Centimia', '35 Novick Point');
insert into DiningHall (diningHall, address) values ('Browsebug', '1251 Cambridge Lane');
insert into DiningHall (diningHall, address) values ('Tagpad', '0267 Marquette Point');
insert into DiningHall (diningHall, address) values ('Eayo', '5313 Sachtjen Terrace');
insert into DiningHall (diningHall, address) values ('Oozz', '9164 Texas Alley');
insert into DiningHall (diningHall, address) values ('Tazzy', '87371 Park Meadow Park');
insert into DiningHall (diningHall, address) values ('Abatz', '1779 Anderson Avenue');
insert into DiningHall (diningHall, address) values ('Cogilith', '39503 Debs Terrace');
insert into DiningHall (diningHall, address) values ('Twitterbeat', '4 Shopko Street');
insert into DiningHall (diningHall, address) values ('Topiczoom', '21630 Packers Hill');
insert into DiningHall (diningHall, address) values ('Youbridge', '12630 Dexter Plaza');
insert into DiningHall (diningHall, address) values ('Skalith', '8149 Loftsgordon Park');
insert into DiningHall (diningHall, address) values ('Thoughtblab', '94 Bay Hill');
insert into DiningHall (diningHall, address) values ('Livetube', '437 Coolidge Terrace');
insert into DiningHall (diningHall, address) values ('Skipfire', '2911 Mcguire Park');
insert into DiningHall (diningHall, address) values ('Npath', '973 Dapin Point');
insert into DiningHall (diningHall, address) values ('Pixope', '5 Waubesa Park');
insert into DiningHall (diningHall, address) values ('Realblab', '356 Dorton Pass');
insert into DiningHall (diningHall, address) values ('Cogilith', '3973 Porter Crossing');
insert into DiningHall (diningHall, address) values ('Flashspan', '99 Hauk Street');
insert into DiningHall (diningHall, address) values ('Bluejam', '6 Merchant Way');
insert into DiningHall (diningHall, address) values ('Brainbox', '0 Sutteridge Point');
insert into DiningHall (diningHall, address) values ('Divape', '0 Westridge Lane');
insert into DiningHall (diningHall, address) values ('Babbleblab', '2060 Mesta Court');
insert into DiningHall (diningHall, address) values ('Mymm', '76 Vera Drive');
insert into DiningHall (diningHall, address) values ('Npath', '80 Butterfield Point');
insert into DiningHall (diningHall, address) values ('Layo', '867 Susan Junction');
insert into DiningHall (diningHall, address) values ('Browsedrive', '9 Mockingbird Way');
insert into DiningHall (diningHall, address) values ('Thoughtbeat', '53350 Milwaukee Court');
insert into DiningHall (diningHall, address) values ('Ooba', '484 Glendale Pass');
insert into DiningHall (diningHall, address) values ('Skyndu', '62 Eliot Plaza');
insert into DiningHall (diningHall, address) values ('Lajo', '9604 Raven Parkway');
insert into DiningHall (diningHall, address) values ('Skinder', '06 Grim Point');
insert into DiningHall (diningHall, address) values ('Trudeo', '4238 Old Gate Hill');
insert into DiningHall (diningHall, address) values ('Meetz', '305 Hagan Parkway');
insert into DiningHall (diningHall, address) values ('Agimba', '0 Oneill Junction');
insert into DiningHall (diningHall, address) values ('Eamia', '300 Westend Center');
insert into DiningHall (diningHall, address) values ('Centimia', '850 Loomis Drive');
insert into DiningHall (diningHall, address) values ('Tavu', '6830 Manufacturers Terrace');
insert into DiningHall (diningHall, address) values ('Photobean', '23 Eliot Center');
insert into DiningHall (diningHall, address) values ('Buzzdog', '68083 Judy Avenue');
insert into DiningHall (diningHall, address) values ('Devshare', '6183 2nd Place');
insert into DiningHall (diningHall, address) values ('Plajo', '911 Fair Oaks Trail');
insert into DiningHall (diningHall, address) values ('Shufflester', '52147 Cody Road');
insert into DiningHall (diningHall, address) values ('Rooxo', '5 Melody Center');
insert into DiningHall (diningHall, address) values ('Quaxo', '0 Armistice Trail');
insert into DiningHall (diningHall, address) values ('Meemm', '929 Lakewood Gardens Alley');
insert into DiningHall (diningHall, address) values ('Blogspan', '26 Kedzie Alley');
insert into DiningHall (diningHall, address) values ('Tagtune', '23 Londonderry Street');
insert into DiningHall (diningHall, address) values ('Oyonder', '51889 Meadow Ridge Drive');
insert into DiningHall (diningHall, address) values ('Npath', '1344 Mesta Street');
insert into DiningHall (diningHall, address) values ('Realcube', '11380 Morning Pass');
insert into DiningHall (diningHall, address) values ('Tambee', '77 Golden Leaf Park');
insert into DiningHall (diningHall, address) values ('Fivespan', '0 Ridgeview Crossing');
insert into DiningHall (diningHall, address) values ('Fiveclub', '4 Bellgrove Avenue');
insert into DiningHall (diningHall, address) values ('Quatz', '8279 Moland Trail');
insert into DiningHall (diningHall, address) values ('Gigabox', '7 High Crossing Street');
insert into DiningHall (diningHall, address) values ('Riffpath', '6729 Onsgard Park');
insert into DiningHall (diningHall, address) values ('Flipstorm', '09037 Kennedy Drive');
insert into DiningHall (diningHall, address) values ('Realbridge', '5094 Goodland Alley');
insert into DiningHall (diningHall, address) values ('Geba', '22 Cordelia Avenue');
insert into DiningHall (diningHall, address) values ('Meetz', '112 Chive Pass');
insert into DiningHall (diningHall, address) values ('Skinder', '23 Loomis Crossing');
insert into DiningHall (diningHall, address) values ('Jaxbean', '08196 Cascade Circle');
insert into DiningHall (diningHall, address) values ('Chatterpoint', '0949 Annamark Hill');
insert into DiningHall (diningHall, address) values ('Snaptags', '99 Old Shore Pass');
insert into DiningHall (diningHall, address) values ('Dablist', '932 Stang Junction');
insert into DiningHall (diningHall, address) values ('Gabvine', '3 Declaration Junction');
insert into DiningHall (diningHall, address) values ('Yombu', '758 Hollow Ridge Way');
insert into DiningHall (diningHall, address) values ('Bluezoom', '8411 Maryland Crossing');
insert into DiningHall (diningHall, address) values ('Livetube', '6991 Buell Trail');
insert into DiningHall (diningHall, address) values ('Ntags', '232 Pierstorff Drive');
insert into DiningHall (diningHall, address) values ('Gabvine', '3567 Westport Way');
insert into DiningHall (diningHall, address) values ('Rhyloo', '35836 Hanover Court');
insert into DiningHall (diningHall, address) values ('Camido', '14824 Havey Trail');
insert into DiningHall (diningHall, address) values ('Kamba', '5 Emmet Street');
insert into DiningHall (diningHall, address) values ('Vitz', '71906 Green Ridge Plaza');
insert into DiningHall (diningHall, address) values ('Flipopia', '5843 Harbort Trail');
insert into DiningHall (diningHall, address) values ('Jazzy', '59 Cordelia Parkway');
insert into DiningHall (diningHall, address) values ('Myworks', '8294 Sycamore Circle');
insert into DiningHall (diningHall, address) values ('Jaloo', '5 Morning Circle');
insert into DiningHall (diningHall, address) values ('Dabfeed', '606 Washington Street');
insert into DiningHall (diningHall, address) values ('Kwideo', '83424 Crowley Park');
insert into DiningHall (diningHall, address) values ('Dazzlesphere', '88690 Corscot Terrace');
insert into DiningHall (diningHall, address) values ('Rhyloo', '1 Fisk Pass');
insert into DiningHall (diningHall, address) values ('Trilith', '075 Clarendon Trail');
insert into DiningHall (diningHall, address) values ('Tekfly', '399 Lighthouse Bay Crossing');
insert into DiningHall (diningHall, address) values ('Jabbercube', '0 Claremont Junction');
insert into DiningHall (diningHall, address) values ('Zava', '70 Dapin Terrace');
insert into DiningHall (diningHall, address) values ('Brightbean', '2676 Westerfield Court');
insert into DiningHall (diningHall, address) values ('Babbleblab', '50 Thompson Junction');
insert into DiningHall (diningHall, address) values ('Jabberstorm', '4 Rieder Way');
insert into DiningHall (diningHall, address) values ('Izio', '9396 Swallow Alley');
insert into DiningHall (diningHall, address) values ('Quatz', '52617 2nd Terrace');
insert into DiningHall (diningHall, address) values ('Jamia', '54 Meadow Valley Pass');
insert into DiningHall (diningHall, address) values ('Realblab', '41134 Gulseth Terrace');
insert into DiningHall (diningHall, address) values ('Yoveo', '12 Maryland Crossing');
insert into DiningHall (diningHall, address) values ('Feedspan', '19163 Lakeland Park');
insert into DiningHall (diningHall, address) values ('Camido', '64053 Canary Pass');
insert into DiningHall (diningHall, address) values ('Browsezoom', '1306 3rd Alley');
insert into DiningHall (diningHall, address) values ('Oyonder', '8 Fordem Lane');
insert into DiningHall (diningHall, address) values ('Skipfire', '050 Orin Lane');
insert into DiningHall (diningHall, address) values ('Devbug', '6122 Mesta Parkway');
insert into DiningHall (diningHall, address) values ('Thoughtbeat', '64 Pleasure Street');
insert into DiningHall (diningHall, address) values ('Chatterbridge', '879 Lyons Circle');
insert into DiningHall (diningHall, address) values ('Viva', '6 Alpine Circle');
insert into DiningHall (diningHall, address) values ('Eimbee', '802 Muir Alley');
insert into DiningHall (diningHall, address) values ('Jaxnation', '3294 Harbort Road');
insert into DiningHall (diningHall, address) values ('Jaxworks', '6165 Linden Drive');
insert into DiningHall (diningHall, address) values ('Quinu', '06 Wayridge Point');
insert into DiningHall (diningHall, address) values ('Npath', '68 Sherman Terrace');
insert into DiningHall (diningHall, address) values ('Skipfire', '51092 Dottie Avenue');
insert into DiningHall (diningHall, address) values ('Twimm', '527 Rieder Terrace');
insert into DiningHall (diningHall, address) values ('Plajo', '303 Moulton Court');
insert into DiningHall (diningHall, address) values ('Topdrive', '1 Sunnyside Lane');
insert into DiningHall (diningHall, address) values ('Twitterbridge', '591 Park Meadow Hill');
insert into DiningHall (diningHall, address) values ('Roombo', '152 Doe Crossing Parkway');
insert into DiningHall (diningHall, address) values ('Voonte', '57150 Miller Place');
insert into DiningHall (diningHall, address) values ('Twitterwire', '78 Garrison Pass');
insert into DiningHall (diningHall, address) values ('Linklinks', '20274 Victoria Trail');
insert into DiningHall (diningHall, address) values ('Twitterwire', '35 Gerald Junction');
insert into DiningHall (diningHall, address) values ('Twitterwire', '5883 Hallows Avenue');
insert into DiningHall (diningHall, address) values ('Oyonder', '506 Dawn Trail');
insert into DiningHall (diningHall, address) values ('Tagopia', '74879 Tony Plaza');
insert into DiningHall (diningHall, address) values ('Tagtune', '2 Melvin Hill');
insert into DiningHall (diningHall, address) values ('Demizz', '67 Dayton Plaza');
insert into DiningHall (diningHall, address) values ('Blogspan', '1016 Bultman Pass');
insert into DiningHall (diningHall, address) values ('Devify', '3640 Spohn Center');
insert into DiningHall (diningHall, address) values ('Dabtype', '93 Kinsman Junction');
insert into DiningHall (diningHall, address) values ('Camido', '38 Ruskin Hill');
insert into DiningHall (diningHall, address) values ('Quinu', '20 Golf View Circle');
insert into DiningHall (diningHall, address) values ('Photobug', '8 Victoria Terrace');
insert into DiningHall (diningHall, address) values ('Jabberstorm', '569 6th Parkway');
insert into DiningHall (diningHall, address) values ('Devify', '304 Steensland Place');
insert into DiningHall (diningHall, address) values ('Edgeify', '74857 Vahlen Center');
insert into DiningHall (diningHall, address) values ('Skynoodle', '120 Hansons Court');
insert into DiningHall (diningHall, address) values ('Jabbersphere', '41 Sommers Way');
insert into DiningHall (diningHall, address) values ('Bubblebox', '9452 Chive Park');
insert into DiningHall (diningHall, address) values ('Oyope', '96 Monument Lane');
insert into DiningHall (diningHall, address) values ('Linkbuzz', '27550 Ohio Terrace');
insert into DiningHall (diningHall, address) values ('Devbug', '2 Helena Hill');
insert into DiningHall (diningHall, address) values ('Avamm', '4 Anthes Plaza');
insert into DiningHall (diningHall, address) values ('Ailane', '13 Manufacturers Road');
insert into DiningHall (diningHall, address) values ('Voonte', '253 Brown Junction');
insert into DiningHall (diningHall, address) values ('Buzzshare', '87177 Basil Hill');
insert into DiningHall (diningHall, address) values ('Rhybox', '06 Hanson Way');
insert into DiningHall (diningHall, address) values ('Skipfire', '73834 Farragut Road');
insert into DiningHall (diningHall, address) values ('Ooba', '9062 Gale Pass');
insert into DiningHall (diningHall, address) values ('Twinder', '23148 Manufacturers Street');
insert into DiningHall (diningHall, address) values ('Tazzy', '3060 Cody Drive');
insert into DiningHall (diningHall, address) values ('Dynava', '16 Onsgard Terrace');
insert into DiningHall (diningHall, address) values ('Mymm', '67 Browning Point');
insert into DiningHall (diningHall, address) values ('Kanoodle', '75 Ohio Terrace');
insert into DiningHall (diningHall, address) values ('Rhynoodle', '5964 Karstens Street');
insert into DiningHall (diningHall, address) values ('Avamm', '761 Bunting Trail');
insert into DiningHall (diningHall, address) values ('Realcube', '6874 Fremont Avenue');
insert into DiningHall (diningHall, address) values ('Camimbo', '87 Fisk Court');
insert into DiningHall (diningHall, address) values ('Kamba', '3 Buhler Drive');
insert into DiningHall (diningHall, address) values ('Rooxo', '40 Starling Avenue');
insert into DiningHall (diningHall, address) values ('Katz', '2977 8th Parkway');
insert into DiningHall (diningHall, address) values ('Skilith', '52700 Talmadge Park');
insert into DiningHall (diningHall, address) values ('Skaboo', '1659 Village Green Drive');
insert into DiningHall (diningHall, address) values ('Oyonder', '5705 Larry Pass');
insert into DiningHall (diningHall, address) values ('Devcast', '2 7th Plaza');
insert into DiningHall (diningHall, address) values ('Topicware', '430 Hallows Circle');
insert into DiningHall (diningHall, address) values ('Brainsphere', '933 Bashford Drive');
insert into DiningHall (diningHall, address) values ('Flipbug', '2323 Spohn Avenue');
insert into DiningHall (diningHall, address) values ('Viva', '44 Corry Way');
insert into DiningHall (diningHall, address) values ('Reallinks', '60491 Bultman Avenue');
insert into DiningHall (diningHall, address) values ('Dynabox', '9637 Fuller Place');
insert into DiningHall (diningHall, address) values ('Yoveo', '8 Sugar Court');
insert into DiningHall (diningHall, address) values ('Wikivu', '683 Redwing Circle');
insert into DiningHall (diningHall, address) values ('Topiclounge', '3 Raven Center');
insert into DiningHall (diningHall, address) values ('Trilia', '3 Shasta Way');
insert into DiningHall (diningHall, address) values ('Chatterbridge', '9943 Mesta Point');
insert into DiningHall (diningHall, address) values ('Devpulse', '04093 Golf Course Trail');
insert into DiningHall (diningHall, address) values ('Linktype', '756 Merry Terrace');
insert into DiningHall (diningHall, address) values ('Aimbu', '0 Grayhawk Drive');
insert into DiningHall (diningHall, address) values ('Wordpedia', '71880 Sutteridge Street');
insert into DiningHall (diningHall, address) values ('Leexo', '23 Ronald Regan Circle');
insert into DiningHall (diningHall, address) values ('Zoozzy', '064 Eastwood Way');
insert into DiningHall (diningHall, address) values ('Thoughtsphere', '00661 John Wall Way');
insert into DiningHall (diningHall, address) values ('Tambee', '406 Melvin Pass');
insert into DiningHall (diningHall, address) values ('Divanoodle', '32 Starling Pass');
