insert into DiningHall (DiningHall, address) values ('McElroy', '663 Sullivan Point');
insert into DiningHall (DiningHall, address) values ('Carney', '77 Del Mar Drive');
insert into DiningHall (DiningHall, address) values ('Hillside', '5639 Caliangt Terrace');
insert into DiningHall (DiningHall, address) values ('Stuart', '5724 Graedel Way');
insert into DiningHall (DiningHall, address) values ('Hillside', '0 Mitchell Lane');
insert into DiningHall (DiningHall, address) values ('Hillside', '5 Fisk Street');
insert into DiningHall (DiningHall, address) values ('lower', '1174 Prairie Rose Point');
insert into DiningHall (DiningHall, address) values ('Carney', '6 Monterey Street');
insert into DiningHall (DiningHall, address) values ('Lyons', '55394 Barby Junction');
insert into DiningHall (DiningHall, address) values ('Hillside', '28215 Warrior Parkway');
insert into DiningHall (DiningHall, address) values ('Stuart', '22055 Hollow Ridge Court');
insert into DiningHall (DiningHall, address) values ('McElroy', '5455 Packers Parkway');
insert into DiningHall (DiningHall, address) values ('lower', '36 Menomonie Circle');
insert into DiningHall (DiningHall, address) values ('McElroy', '85 Riverside Pass');
insert into DiningHall (DiningHall, address) values ('lower', '39974 Oakridge Lane');
insert into DiningHall (DiningHall, address) values ('Stuart', '61 Coleman Crossing');
insert into DiningHall (DiningHall, address) values ('Carney', '32394 Mendota Junction');
insert into DiningHall (DiningHall, address) values ('McElroy', '750 Sycamore Junction');
insert into DiningHall (DiningHall, address) values ('Stuart', '62 Dapin Street');
insert into DiningHall (DiningHall, address) values ('Hillside', '9305 Michigan Way');
